version: '3.8'

services:

  app:
    build: .
    image: gysborn/new_game
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    expose:
      - 5000
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/code/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always